"""Recursive LLM-powered chain reasoning for complex multi-hop attacks.

This module performs recursive chain analysis by using the LLM to identify
attack chains that span multiple vulnerability types across different components.

Unlike deterministic rules (which require specific tag combinations), the LLM
chain reasoning can:
1. Identify novel chain patterns from findings descriptions
2. Reason about multi-hop attack paths (A → B → C)
3. Assess contextual severity based on finding severity + proximity
4. Generate hypotheses for validation

Public API:
    RecursiveChainAnalysis - LLM-powered chain reasoning
    run_recursive_chain_analysis - Main entry point
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from dataclasses import dataclass, field


@dataclass(frozen=True)
class ChainHypothesis:
    """A chain hypothesis generated by LLM reasoning.

    Attributes:
        id: Stable identifier for the hypothesis.
        name: Human-readable chain name.
        explanation: Why the chain is dangerous.
        trigger_findings: List of finding IDs that form the chain.
        trigger_descriptions: List of finding titles for context.
        hops: Number of hops in the chain.
        new_severity: Calculated severity for the chain.
        confidence: LLM confidence score (0.0-1.0).
        cwe: CWE IDs.
        owasp: OWASP category.
        evidence: Additional context.
        requires_validation: Whether this needs verification.
    """
    id: str
    name: str
    explanation: str
    trigger_findings: list[str]
    trigger_descriptions: list[str]
    hops: int
    new_severity: str
    confidence: float
    cwe: list[str] = field(default_factory=list)
    owasp: list[str] = field(default_factory=list)
    evidence: dict[str, Any] = field(default_factory=dict)
    requires_validation: bool = True


def build_chain_reasoning_prompt(
    findings: list[dict[str, Any]],
    existing_chains: list[dict[str, Any]],
) -> str:
    """Build the prompt for LLM chain reasoning.

    Args:
        findings: List of all findings from scan modules.
        existing_chains: List of existing chain findings.

    Returns:
        Prompt text for the LLM.
    """
    # Build findings context
    findings_context = []
    for i, f in enumerate(findings[:50]):  # Limit to top 50
        context = {
            "id": f.get("id", f"finding_{i}"),
            "title": f.get("title", "Unknown"),
            "description": f.get("description", ""),
            "severity": f.get("severity", "medium"),
            "tags": f.get("tags", []),
        }
        findings_context.append(context)

    # Build existing chains context
    chains_context = []
    for c in existing_chains[:20]:  # Limit to top 20
        context = {
            "name": c.get("name", ""),
            "trigger_ids": c.get("trigger_findings", []),
            "severity": c.get("new_severity", "medium"),
            "delta": c.get("severity_delta", 0),
        }
        chains_context.append(context)

    prompt = f"""You are a security chain analysis expert. Your task is to identify multi-hop attack chains that were not detected by deterministic rules.

## Context

### Findings ({len(findings)} total, showing top {min(50, len(findings))}):
"""
    for f in findings_context:
        prompt += f"- [{f['severity'].upper()}] {f['title']} (tags: {', '.join(f['tags'])})\n"

    if existing_chains:
        prompt += f"\n### Existing Chains ({len(chains_context)} total, showing top {min(20, len(chains_context))}):\n"
        for c in chains_context:
            prompt += f"- [{c['severity']}] {c['name']} (delta: +{c['delta']})\n"

    prompt += """
## Task

Identify multi-hop attack chains from the findings. For each chain:
1. Identify a sequence of 2-4 vulnerabilities that can be chained together
2. Explain why they form a valid attack chain
3. Assign appropriate CWE and OWASP mappings
4. Rate your confidence in the chain (0.0-1.0)

## Output Format

Return a JSON array with the following structure:
[
  {
    "name": "chain_name_with_underscores",
    "explanation": "Detailed explanation of why this chain is dangerous",
    "trigger_finding_ids": ["finding_id_1", "finding_id_2"],
    "hops": 2,
    "new_severity": "critical|high|medium|low",
    "confidence": 0.9,
    "cwe": ["CWE-287", "CWE-284"],
    "owasp": ["A01:2021-Broken Access Control"],
    "requires_validation": true
  }
]

## Constraints

- Each chain must be plausible and logically sound
- Chains must reference actual finding IDs from the context
- Focus on novel chains not already covered by existing chains
- Do not hallucinate findings - only use what's in the context
- If no novel chains are possible, return an empty array
"""

    return prompt


def run_recursive_chain_analysis(
    findings: list[dict[str, Any]],
    existing_chains: list[dict[str, Any]] | None = None,
    model: str | None = None,
    provider: str | None = None,
    max_hops: int = 3,
) -> list[ChainHypothesis]:
    """Run recursive chain analysis using LLM reasoning.

    Args:
        findings: List of all findings from scan modules.
        existing_chains: List of existing chain findings.
        model: LLM model name.
        provider: LLM provider name.
        max_hops: Maximum number of hops in chains.

    Returns:
        List of ChainHypothesis objects.
    """
    if existing_chains is None:
        existing_chains = []

    # Build prompt
    prompt = build_chain_reasoning_prompt(findings, existing_chains)

    # Try to run with local LLM first, fall back to cloud
    model = model or "local-qwen36-nvfp4"
    provider = provider or "openai-api"

    print(f"  Running LLM chain reasoning (model: {model}, provider: {provider})...")

    try:
        # Use hermes CLI to run chain reasoning
        import subprocess
        import tempfile

        # Write prompt to temp file
        with tempfile.NamedTemporaryFile(mode="w", suffix=".md", delete=False) as f:
            f.write(prompt)
            prompt_path = f.name

        # Run with hermes CLI
        result = subprocess.run(
            [
                "hermes", "chat",
                "--provider", provider,
                "--model", model,
                "--max-turns", "5",
                "--toolsets", "file",
                "--ignore-rules-unsafe",
                "--yolo",
                f"@{prompt_path}"
            ],
            capture_output=True, text=True, timeout=180
        )

        # Clean up
        Path(prompt_path).unlink(missing_ok=True)

        if result.returncode != 0:
            print(f"    Chain reasoning failed: {result.stderr[:200]}")
            return []

        # Parse LLM response
        llm_output = result.stdout

        # Try to extract JSON from response
        import re
        json_match = re.search(r'\[\s*\{.*\}\s*\]', llm_output, re.DOTALL)
        if json_match:
            chains_json = json.loads(json_match.group())
        else:
            print("    No JSON found in LLM response")
            return []

        # Convert to ChainHypothesis objects
        hypotheses: list[ChainHypothesis] = []
        run_id = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")

        for i, chain_data in enumerate(chains_json):
            # Parse triggers from finding IDs
            trigger_ids = chain_data.get("trigger_finding_ids", [])
            trigger_descs = []
            for fid in trigger_ids:
                for f in findings:
                    if f.get("id") == fid or fid in str(f.get("id", "")):
                        trigger_descs.append(f.get("title", "Unknown"))
                        break

            if not trigger_descs and trigger_ids:
                trigger_descs = trigger_ids  # Use IDs as descriptions if not found

            hypothesis = ChainHypothesis(
                id=f"chain-llm-{run_id}-{i:03d}",
                name=chain_data.get("name", "unknown_chain"),
                explanation=chain_data.get("explanation", ""),
                trigger_findings=trigger_ids,
                trigger_descriptions=trigger_descs,
                hops=chain_data.get("hops", 2),
                new_severity=chain_data.get("new_severity", "medium"),
                confidence=chain_data.get("confidence", 0.5),
                cwe=chain_data.get("cwe", []),
                owasp=chain_data.get("owasp", []),
                evidence={
                    "llm_model": model,
                    "llm_provider": provider,
                    "analysis_type": "recursive_chain_reasoning",
                    "max_hops": max_hops,
                    "total_findings": len(findings),
                    "existing_chains": len(existing_chains),
                },
                requires_validation=True,
            )
            hypotheses.append(hypothesis)

        print(f"    LLM identified {len(hypotheses)} chain hypothesis/hypotheses:")
        for h in hypotheses:
            print(f"      [{h.new_severity}] {h.name} (confidence: {h.confidence:.2f})")

        return hypotheses

    except Exception as e:
        print(f"    Chain reasoning error: {e}")
        import traceback
        traceback.print_exc()
        return []
